# SSSStatic Configuration - Development Testing
site:
  name: "SSSStatic Dev Server - UPDATED"
  description: "Testing the enhanced dev server functionality with file watching"
  colorMode: "dark"

# TopBar navigation with CTA button
_topbar:
  title: "Welcome to Sssstatic"
  cta: "Get Started"
  link: "#contact"

# Sinema Terminal Component
_sinema:
  terminal_text: "hello world"
  boot_delay: 2000