# SSSStatic Configuration - Development Testing
site:
  name: "SSSStatic Dev Server - UPDATED"
  description: "Testing the enhanced dev server functionality with file watching"
  colorMode: "dark"

# TopBar navigation with CTA button
_topbar:
  title: "sssstatic"
  titleFont: "Original Surfer"
  cta: "Get Started"
  link: "#contact"
  size: "large"

# Multiple rows - each row is a separate section
_row:
  - _column:
    - _sinema:
        title: "SINEMA TERMINAL"
        subtitle: "Vintage Computing Experience"
        terminal_text: "Nice to meet you"
        boot_delay: 2000
    - _sslogan:
        heading: "Build this website with SSSStatic"
        subheading: "Go live in thirty seconds. 🚀"
        paragraphs:
          - "From idea to a beautiful, responsive website in just a few lines of text. Perfect for portfolios, docs, and landing pages."
  - _column:
    - _component:
        content:
          - _text:
              align: "center"
              content: "Open Source"
              type: "h1"
              size: "xlarge"
              weight: "light"
              # paddingBlock: "1rem"
              lineHeight: "small"
          - _text:
              content: "The project is open source and free to use. Who knows what you'll build with it."
              type: "p"
              size: "medium"
              weight: "thin"
              lineHeight: "medium"
              paddingBlock: "0.5rem"
          - _button:
              align: "left"
              text: "View on GitHub"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              size: "medium"
              icon: "star"
          - _button:
              align: "left"
              text: "View on GitHub"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              variant: "link"
              size: "medium"
              # icon: "star"
    - _component:
        bgColor: "#1B1F23"
        content:
          - _sticker:
              align: "center"
              name: "rocket"
              size: "large"
              position: "center"
              animation: "bounce"
          - _text:
              content: "People don't appreciate the value of a good sticker."
              type: "p"
              size: "medium"
              weight: "light"
              lineHeight: "medium"
          - _button:
              align: "left"
              text: "View Sticker Gallary"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              variant: "link"
              size: "medium"
    - _component:
        bgColor: "#1B1F23"
        content: 
          - _sticker:
              align: "center"
              name: "computer"
              size: "large"
              position: "center"
          - _text:
              content: "Build in dev server mode for instant gratification. Imagine it. Ship it."
              type: "p"
              size: "medium"
              weight: "light"
              lineHeight: "medium"
          - _button:
              align: "left"
              text: "View Examples"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              variant: "link"
              size: "medium"
    - _component:
        bgColor: "#1B1F23"
        content: 
          - _sticker:
              align: "center"
              name: "cmoon"
              size: "large"
              position: "center"
          - _text:
              content: "Build in dev server mode for instant gratification. Imagine it. Ship it."
              type: "p"
              size: "medium"
              weight: "light"
              lineHeight: "medium"
          - _button:
              align: "left"
              text: "View Examples"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              variant: "link"
              size: "medium"

_showcase:
        image: "statie.png"
        direction: "right"
        title: "Why Static Sites Are Awesome"
        subtitle: "Fast, secure, and reliable"
        steps:
            - emoji: "⚡"
              text: "Lightning Fast Performance"
              description: "No server-side processing means instant page loads and better user experience"
            - emoji: "🔒"
              text: "Enhanced Security"
              description: "No database or server-side code means fewer attack vectors and vulnerabilities"
            - emoji: "💰"
              text: "Cost Effective Hosting"
              description: "Host anywhere for free or pennies - CDNs, GitHub Pages, Netlify, Vercel"
            - emoji: "📈"
              text: "Better SEO & Reliability"
              description: "Faster loading times improve search rankings and uptime is nearly 100%"
        button_text: "Get Started Today"
        button_url: "#contact"
        button_size: "large"