# SSSStatic Configuration - Development Testing
site:
  name: "SSSStatic Dev Server - UPDATED"
  description: "Testing the enhanced dev server functionality with file watching"
  colorMode: "dark"

# TopBar navigation with CTA button
_topbar:
  title: "sssstatic"
  titleFont: "Original Surfer"
  cta: "Get Started"
  link: "#contact"
  size: "large"

# Multiple rows - each row is a separate section
_row:
  - _column:
    - _video:
        src: "sample.mp4"
        controls: false
        autoplay: true
        loop: false
        muted: true
        borderRadius: "30px"
        zoom: "1.1"
    - _component:
        content:
          - _text:
              content: "Publish at the speed of static."
              spacerTop: "4rem"
              type: "h1"
              size: "xxlarge"
              fontWeight: "700"
              fontFamily: "heading"
              letterSpacing: "tight"
              align: "left"
              lineHeight: "small"
              marginBottom: "1rem"
          - _text:
              content: "Code less. Deploy more. 🚀"
              type: "h2"
              size: "large"
              fontWeight: "500"
              fontFamily: "heading"
              align: "left"
              lineHeight: "medium"
              marginBottom: "1rem"
          - _text:
              content: "From idea to a beautiful, responsive website in just a few lines of text. Perfect for portfolios, docs, and landing pages."
              type: "p"
              size: "medium"
              fontWeight: "400"
              fontFamily: "primary"
              align: "left"
              lineHeight: "medium"
  - _column:
    - _component:
        content:
          - _text:
              align: "center"
              content: "Open Source"
              type: "h1"
              size: "xlarge"
              weight: "light"
              # paddingBlock: "1rem"
              lineHeight: "small"
          - _text:
              content: "MIT Licensed and free to use. Who knows what you'll build with it."
              type: "p"
              size: "medium"
              weight: "normal"
              lineHeight: "medium"
              paddingBlock: "0.5rem"
          - _button:
              align: "left"
              text: "View on GitHub"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              size: "medium"
              icon: "star"
          - _button:
              align: "left"
              text: "Report an issue"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              variant: "link"
              size: "medium"
              # icon: "star"
    - _component:
        bgColor: "#1B1F23"
        content:
          - _sticker:
              align: "center"
              name: "rocket"
              size: "large"
              position: "center"
            #   animation: "bounce"
          - _text:
              content: "People don't appreciate the value of a good sticker."
              type: "p"
              size: "medium"
              weight: "light"
              lineHeight: "medium"
          - _button:
              align: "left"
              text: "View Sticker Gallary"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              variant: "link"
              size: "medium"
    - _component:
        bgColor: "#1B1F23"
        content: 
          - _sticker:
              align: "center"
              name: "computer"
              size: "large"
              position: "center"
          - _text:
              content: "Build in dev server mode for instant gratification. Imagine it. Ship it."
              type: "p"
              size: "medium"
              weight: "light"
              lineHeight: "medium"
          - _button:
              align: "left"
              text: "View Examples"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              variant: "link"
              size: "medium"
    - _component:
        bgColor: "#1B1F23"
        content: 
          - _sticker:
              align: "center"
              name: "cmoon"
              size: "large"
              position: "center"
          - _text:
              content: "Build in dev server mode for instant gratification. Imagine it. Ship it."
              type: "p"
              size: "medium"
              weight: "light"
              lineHeight: "medium"
          - _button:
              align: "left"
              text: "View Examples"
              url: "https://github.com/yourusername/sssstatic"
              style: "primary"
              variant: "link"
              size: "medium"

_slick:
  title: "Get results that speak for themselves"
#   color: "#e1e8ed" 
  highlightText: "results"
#   highlightColor: "black" 
  image: "phone.png"
  bgColor: "#1B1F23"
  benefits:
    - icon: "📈"
      title: "Get Noticed. Get Chosen."
      description: "Better photos = more eyeballs. It's a numbers game, and we're here to make you win."
    - icon: "🥂"
      title: "Actually Go On Dates"
      description: "Enough with the pen-pal stuff. Let's get you off the app and into a bar with someone interesting. Regularly."
    - icon: "😍"
      title: "Attract Your Type. For Real."
      description: "Stop wasting time on \"meh.\" Start matching with people you're genuinely excited to see. Yeah, you can punch above your weight."
    - icon: "💬"
      title: "Conversations That Don't Suck"
      description: "Forget \"hey\" and the crickets that follow. A killer profile makes you instantly more interesting. They'll be hitting you up."

_widescreen_spotlight:
  image: "beetle.png"
  title: "Blossom"
  description: "<em>Your</em> creative agency."
  textPosition: "left"
  buttons:
    - text: "Get In Touch"
      url: "#meet_juily"
      style: "primary"
