# SSSStatic Configuration - Development Testing
site:
  name: "SSSStatic Dev Server - UPDATED"
  description: "Testing the enhanced dev server functionality with file watching"
  colorMode: "dark"

# TopBar navigation with CTA button
_topbar:
  title: "Welcome to Sssstatic"
  titleFont: "Bitcount Grid Double"
  cta: "Get Started"
  link: "#contact"

# Sinema Terminal Component
_sinema:
  title: "SINEMA TERMINAL"
  subtitle: "Vintage Computing Experience"
  terminal_text: "Nice to meet you"
  boot_delay: 2000
