# SSSStatic Configuration - Development Testing
site:
  name: "SSSStatic Dev Server - UPDATED"
  description: "Testing the enhanced dev server functionality with file watching"
  colorMode: "dark"

# TopBar navigation with CTA button
_topbar:
  title: "sssstatic"
  titleFont: "Original Surfer"
  cta: "Get Started"
  link: "#contact"
  size: "large"

# Multiple rows - each row is a separate section
_row:
  - _column:
    - _sinema:
        title: "SINEMA TERMINAL"
        subtitle: "Vintage Computing Experience"
        terminal_text: "Nice to meet you"
        boot_delay: 2000
    - _sieve:
        heading: "Build this website with SSSStatic 🪄"
        subheading: "Go live in thirty seconds. 🚀"
        paragraphs:
          - "From idea to a beautiful, responsive website in just a few lines of text. Perfect for portfolios, docs, and landing pages."
  - _column:
    - _component:
        html: "<h1>Column 1</h1>"
    - _component:
        html: "<h1>Column 2</h1>"
    - _component:
        html: "<h1>Column 3</h1>"
    - _component:
        html: "<h1>Column 4</h1>"
