#!/usr/bin/env python3
# sssstatic.py
"""
SSSSStatic - A Simple Static Site Generator
"""

import argparse
import os
import sys
from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt

console = Console()


def create_new_project():
    """Create a new static site project with wizard."""
    console.print("\n[bold blue]🚀 SSSSStatic Project Creator[/bold blue]")
    console.print("Let's create your new static site!\n")

    # Get project name
    project_name = Prompt.ask("What is the name of your project?")
    if not project_name.strip():
        console.print("[red]Error: Project name cannot be empty[/red]")
        return

    # Get project location
    current_dir = os.getcwd()
    console.print(f"[dim]Default location: {current_dir}[/dim]")
    project_location = Prompt.ask(
        "Where do you want the project to be located?",
        default=current_dir
    )

    # Create full project path
    project_path = Path(project_location) / project_name

    # Check if directory already exists
    if project_path.exists():
        console.print(f"[red]Error: Directory '{project_path}' already exists![/red]")
        return

    try:
        # Create project structure
        console.print(f"\n[yellow]Creating project '{project_name}' at {project_path}...[/yellow]")

        # Create main project directory
        project_path.mkdir(parents=True, exist_ok=True)

        # Create www directory
        www_dir = project_path / "www"
        www_dir.mkdir(exist_ok=True)

        # Create _config.yml
        config_content = f"""# SSSSStatic Configuration
site_name: "{project_name}"
description: "A static site generated with SSSSStatic"
author: "Your Name"
url: ""

# Build settings
output_dir: "_site"
source_dir: "www"

# Theme settings
theme:
  name: "default"
"""

        config_file = project_path / "_config.yml"
        config_file.write_text(config_content)

        # Create index.html
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name} - Generated by SSSSStatic</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }}
        
        .container {{
            background: white;
            padding: 3rem;
            border-radius: 10px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
            text-align: center;
            max-width: 600px;
            margin: 2rem;
        }}
        
        h1 {{
            color: #764ba2;
            margin-bottom: 1rem;
            font-size: 2.5rem;
        }}
        
        .subtitle {{
            color: #666;
            font-size: 1.2rem;
            margin-bottom: 2rem;
        }}
        
        .badge {{
            display: inline-block;
            background: #667eea;
            color: white;
            padding: 0.5rem 1rem;
            border-radius: 20px;
            font-size: 0.9rem;
            margin-top: 1rem;
        }}
        
        .footer {{
            margin-top: 2rem;
            padding-top: 2rem;
            border-top: 1px solid #eee;
            color: #999;
            font-size: 0.9rem;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to {project_name}!</h1>
        <p class="subtitle">Your static site has been successfully generated</p>
        <p>This site was created using <strong>SSSSStatic</strong>, a simple static site generator.</p>
        <div class="badge">Generated by SSSSStatic 🚀</div>
        <div class="footer">
            <p>Check the browser console for a hello message!</p>
            <p>Edit <code>www/index.html</code> to customize this page.</p>
        </div>
    </div>
    
    <script>
        console.log('🎉 Hello World from SSSSStatic!');
        console.log('Your static site is ready to be customized.');
        console.log('Project: {project_name}');
        console.log('Generated at:', new Date().toISOString());
    </script>
</body>
</html>"""

        index_file = www_dir / "index.html"
        index_file.write_text(html_content)

        # Success message
        console.print(f"[green]✅ Project '{project_name}' created successfully![/green]")
        console.print(f"[dim]Location: {project_path}[/dim]")
        console.print("\n[yellow]Next steps:[/yellow]")
        console.print(f"  cd {project_name}")
        console.print("  # Edit www/index.html to customize your site")
        console.print("  # Run 'sssstatic build' to generate your site")

    except Exception as e:
        console.print(f"[red]Error creating project: {e}[/red]")


def main():
    """Main entry point for the static site generator."""
    parser = argparse.ArgumentParser(description="SSSSStatic - A Simple Static Site Generator")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # Create command
    create_parser = subparsers.add_parser("create", help="Create a new project")
    create_parser.add_argument("type", choices=["new"], help="Type of project to create")

    # Parse arguments
    args = parser.parse_args()

    if args.command == "create" and args.type == "new":
        create_new_project()
    elif args.command is None:
        console.print("[bold bright_green]>> SSSSStatic ONLINE[/bold bright_green]", style="bold green")
        console.print("[dim bright_blue]>> Static site generator initialized successfully[/dim bright_blue]",
                      style="dim")
        console.print("[dim]>> Use 'sssstatic create new' to initialize new project[/dim]")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
