# SSSStatic Configuration - Pinterest Test
site:
  name: "Pinterest Masonry Test"

_title: "Pinterest-Style Masonry Layout"

# Pinterest masonry layout with sample images
_pinterest:
  - title: "Beautiful Landscape"
    description: "A stunning mountain vista with crystal clear lakes"
    url: "https://example.com/landscape"
    
  - title: "Urban Architecture"
    description: "Modern city skyline at golden hour"
    url: "https://example.com/architecture"
    
  - title: "Nature Photography"
    description: "Close-up of vibrant flowers in a garden"
    url: "https://example.com/nature"
    
  - title: "Abstract Art"
    description: "Colorful geometric patterns and shapes"
    url: "https://example.com/abstract"
    
  - title: "Food Photography"
    description: "Delicious homemade pasta with fresh ingredients"
    url: "https://example.com/food"
    
  - title: "Travel Destination"
    description: "Exotic beach paradise with turquoise waters"
    url: "https://example.com/travel"
    
  - title: "Technology"
    description: "Futuristic city with neon lights and flying cars"
    url: "https://example.com/tech"
    
  - title: "Minimalist Design"
    description: "Clean, simple design with perfect symmetry"
    url: "https://example.com/minimal"
    
  - title: "Vintage Style"
    description: "Retro aesthetic with warm, nostalgic tones"
    url: "https://example.com/vintage"
    
  - title: "Space Exploration"
    description: "Galaxy and nebula in deep space"
    url: "https://example.com/space"
    
  - title: "Wildlife"
    description: "Majestic lion in its natural habitat"
    url: "https://example.com/wildlife"
    
  - title: "Fashion"
    description: "Elegant evening wear on a model"
    url: "https://example.com/fashion"

# Regular content section
description: "This page demonstrates the Pinterest-style masonry layout widget. Images are automatically generated using Picsum for variety, and the layout is fully responsive with full-width display."
