# sssstatic/templates.py
"""
Templates module for SSSSStatic - contains all file templates
"""


def get_config_template(project_name):
    """Return the _config.yml template content."""
    return f"""# SSSSStatic Configuration
site_name: "{project_name}"
description: "A static site generated with SSSSStatic"
author: "Your Name"
url: ""

# Build settings
output_dir: "_site"
source_dir: "www"

# Theme settings
theme:
  name: "default"
"""


def get_index_html_template(project_name):
    """Return the index.html template content."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name} - Generated by SSSSStatic</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }}
        
        .container {{
            background: white;
            padding: 3rem;
            border-radius: 10px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
            text-align: center;
            max-width: 600px;
            margin: 2rem;
        }}
        
        h1 {{
            color: #764ba2;
            margin-bottom: 1rem;
            font-size: 2.5rem;
        }}
        
        .subtitle {{
            color: #666;
            font-size: 1.2rem;
            margin-bottom: 2rem;
        }}
        
        .badge {{
            display: inline-block;
            background: #667eea;
            color: white;
            padding: 0.5rem 1rem;
            border-radius: 20px;
            font-size: 0.9rem;
            margin-top: 1rem;
        }}
        
        .footer {{
            margin-top: 2rem;
            padding-top: 2rem;
            border-top: 1px solid #eee;
            color: #999;
            font-size: 0.9rem;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to {project_name}!</h1>
        <p class="subtitle">Your static site has been successfully generated</p>
        <p>This site was created using <strong>SSSSStatic</strong>, a simple static site generator.</p>
        <div class="badge">Generated by SSSSStatic 🚀</div>
        <div class="footer">
            <p>Check the browser console for a hello message!</p>
            <p>Edit <code>www/index.html</code> to customize this page.</p>
        </div>
    </div>
    
    <script>
        console.log('🎉 Hello World from SSSSStatic!');
        console.log('Your static site is ready to be customized.');
        console.log('Project: {project_name}');
        console.log('Generated at:', new Date().toISOString());
    </script>
</body>
</html>"""
